#!/bin/bash

while getopts "c:p:a:" opt
do
    case "${opt}" in
        c) config=${OPTARG};;
        p) pipeline=${OPTARG};;
        a) parameters=${OPTARG};;
    esac
done

cmd="python3 nxfutil.py"

if [[ $config != "" ]] 
then
    cmd="$cmd -c $config"
fi

if [[ $pipeline != "" ]] 
then
    cmd="$cmd -p $pipeline"
fi

if [[ $parameters != "" ]] 
then
    cmd="$cmd -a $parameters"
fi

echo $cmd
$cmd