@org = axgonz
@repo = azure-nextflow
@branch = main
@project = helloWorld
@az_funcName = fcnj6h

GET https://{{az_funcName}}.azurewebsites.net/api/nxfutil HTTP/1.1

###

POST https://{{az_funcName}}.azurewebsites.net/api/nxfutil?whatif=true HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "",
    "parameters_uri": "",
    "auto_delete": true
}

###

POST https://{{az_funcName}}.azurewebsites.net/api/nxfutil HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "",
    "parameters_uri": "",
    "auto_delete": true
}

###

POST https://{{az_funcName}}.azurewebsites.net/api/nxfutil HTTP/1.1
content-type: application/json

{
    "config_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/nextflow.config",
    "pipeline_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/pipeline.nf",
    "parameters_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/parameters.json",
    "auto_delete": true
}