@org = axgonz
@repo = azure-nextflow
@branch = main
@project = helloWorld
@host = localhost:7071

### GET root
GET http://{{host}}/api/nxfutil HTTP/1.1

### GET dispatch
GET http://{{host}}/api/nxfutil/dispatch HTTP/1.1

### POST dispatch (whatif)
POST http://{{host}}/api/nxfutil/dispatch?whatif=true HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "",
    "parameters_uri": "",
    "parameters_json": [
        {
            "name": "foo",
            "value": "bar"
        }
    ],
    "auto_delete": true
}

### POST dispatch
POST http://{{host}}/api/nxfutil/dispatch HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "",
    "parameters_uri": "",
    "auto_delete": true
}

### POST dispatch 
POST https://{{host}}/api/nxfutil/dispatch HTTP/1.1
content-type: application/json

{
    "config_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/nextflow.config",
    "pipeline_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/pipeline.nf",
    "parameters_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/parameters.json",
    "auto_delete": true
}

### GET terminate
GET http://{{host}}/api/nxfutil/terminate HTTP/1.1

### POST terminate (whatif)
POST http://{{host}}/api/nxfutil/terminate?whatif=true HTTP/1.1
content-type: application/json

{
    "ci_name": "nextflow-20230220-0920dcd6-e5de-4ec7-bfcb-54e62ed55cbc"
}

### POST terminate
POST http://{{host}}/api/nxfutil/terminate HTTP/1.1
content-type: application/json

{
    "ci_name": "nextflow-20230220-0920dcd6-e5de-4ec7-bfcb-54e62ed55cbc"
}

### GET status
GET http://{{host}}/api/nxfutil/status HTTP/1.1

### POST status
POST http://{{host}}/api/nxfutil/status HTTP/1.1
content-type: application/json

{
    "summary": true,
    "message_count": 32,
    "dequeue": false
}
