@org = axgonz
@repo = azure-nextflow
@branch = main
@project = helloWorld
@host = localhost:7071

GET http://{{host}}/api/nxfutil HTTP/1.1
###

GET http://{{host}}/api/nxfutil_status HTTP/1.1
###

POST http://{{host}}/api/nxfutil_status HTTP/1.1
content-type: application/json

{
    "message_count": 32,
    "dequeue": true
}
###

DELETE http://{{host}}/api/nxfutil/nextflow-20230220-0920dcd6-e5de-4ec7-bfcb-54e62ed55cbc HTTP/1.1
###

POST http://{{host}}/api/nxfutil?whatif=true HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "",
    "parameters_uri": "",
    "auto_delete": true
}
###

POST http://{{host}}/api/nxfutil HTTP/1.1
content-type: application/json

{
    "config_uri": "",
    "pipeline_uri": "",
    "parameters_uri": "",
    "auto_delete": true
}
###

POST http://{{host}}/api/nxfutil?whatif=true HTTP/1.1
content-type: application/json

{
    "config_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/nextflow.config",
    "pipeline_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/pipeline.nf",
    "parameters_uri": "https://raw.githubusercontent.com/{{org}}/{{repo}}/{{branch}}/nextflow/pipelines/{{project}}/parameters.json",
    "auto_delete": true
}