# Authentication
# Set up the following secret in your GitHub repository: 
#
#   AZURE_MSI
#
# For details on usage of secrets, please refer to:
#  https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

name: All GitHub Workflows

on: 
  workflow_dispatch:
    inputs:
      AZURE_SUBSCRIPTION_ID:
        type: string
        description: 'Azure subscription id'
        required: true
      AZURE_RESOURCEGROUP_NAME:
        type: string
        description: 'Azure resource group name'
        required: true  

jobs:      
  azureTemplates:
    uses: ./.github/workflows/reusable-azure-templates.yml
    with:
      AZURE_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCEGROUP_NAME: ${{ inputs.AZURE_RESOURCEGROUP_NAME }}
    secrets: inherit

  dockerImagesUbuntu:
    needs: azureTemplates
    uses: ./.github/workflows/reusable-docker-images-ubuntu.yml
    with:
      AZURE_KEYVAULT_NAME: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit
    if: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME != '' }} 

  dockerImagesNextflow:
    needs: azureTemplates
    uses: ./.github/workflows/reusable-docker-images-nextflow.yml
    with:
      AZURE_KEYVAULT_NAME: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit
    if: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME != '' }} 

  dockerImagesNxfutil:
    needs: azureTemplates
    uses: ./.github/workflows/reusable-docker-images-nxfutil.yml
    with:
      AZURE_KEYVAULT_NAME: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit  
    if: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME != '' }}      

  azureFunctions:
    needs: azureTemplates
    uses: ./.github/workflows/reusable-azure-functions.yml
    with:
      AZURE_FUNCTIONAPP_NAME: ${{ needs.azureTemplates.outputs.AZURE_FUNCTIONAPP_NAME }}
    secrets: inherit    
    if: ${{ needs.azureTemplates.outputs.AZURE_FUNCTIONAPP_NAME != '' }}

  raiseErrorAZURE_KEYVAULT_NAME:
    needs: azureTemplates
    runs-on: ubuntu-latest 
    if: ${{ needs.azureTemplates.outputs.AZURE_KEYVAULT_NAME = '' }} 
    steps:
    - name: 'Missing AZURE_KEYVAULT_NAME value'
      run: |
        echo "Output variable AZURE_KEYVAULT_NAME from azureTemplates is empty!"
        exit 1

  raiseErrorAZURE_FUNCTIONAPP_NAME:
    needs: azureTemplates
    runs-on: ubuntu-latest 
    if: ${{ needs.azureTemplates.outputs.AZURE_FUNCTIONAPP_NAME = '' }} 
    steps:
    - name: 'Missing AZURE_FUNCTIONAPP_NAME value'
      run: |
        echo "Output variable AZURE_FUNCTIONAPP_NAME from azureTemplates is empty!"
        exit 1