name: Docker - nxfutil

on:
  workflow_dispatch:
    inputs:
      AZURE_KEYVAULT_NAME:
        type: string
        description: 'Azure Key Vault name'
        required: true
  push:
    branches:
    - 'main'
    paths:
    - 'docker/images/nxfutil/Dockerfile'
    - 'azure/functions/rust/src/**'
    - 'azure/functions/rust/Cargo.toml'

jobs:
  dockerImagesNxfutil:
    uses: ./.github/workflows/reusable-docker-images-nxfutil.yml
    with:
      AZURE_KEYVAULT_NAME: ${{ inputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit