name: Docker - ubuntu

on: 
  workflow_dispatch:
    inputs:
      AZURE_KEYVAULT_NAME:
        type: string
        description: 'Azure Key Vault name'
        required: true 
  push:
    branches:
    - 'main'
    paths:
    - 'azure/docker/images/ubuntu/Dockerfile'

jobs:      
  dockerImagesUbuntu:
    uses: ./.github/workflows/reusable-docker-images-ubuntu.yml
    with:
      AZURE_KEYVAULT_NAME: ${{ inputs.AZURE_KEYVAULT_NAME }}
    secrets: inherit
