name: Run Azure - functions

on: 
  workflow_dispatch:
    inputs:
      AZURE_FUNCTIONAPP_NAME: 
        type: string
        description: 'Azure Function App name'
        required: true

jobs:      
  azureFunctions:
    uses: ./.github/workflows/reusable/azure-functions.yml
    with:
      AZURE_FUNCTIONAPP_NAME: ${{ inputs.AZURE_FUNCTIONAPP_NAME }}
    secrets: inherit    